language: python

matrix:
  include:
    - python: 2.7
      env: PYTHON_VERSION=2.7
    - python: 3.7
      env: PYTHON_VERSION=3.7
      dist: xenial
      sudo: true

install:
  - if [[ $PYTHON_VERSION < 3 ]]; then pip install -r requirements27.txt; else pip install -r requirements.txt; fi

script:
  - flake8 cancergeonomics
  - pytest -v .
